/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
        assertEquals(1, 1);
    }
}
